project:
  type: website
  output-dir: .

website:
  title: "Projeto"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: about.qmd
        text: Sobre

format:
  html:
    theme: cosmo
    css: styles.css
    lang: pt-BR

